# Generated by Django 3.2.7 on 2021-09-22 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_rename_content_items_data'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Items',
            new_name='Task',
        ),
    ]
